version: '3.8'
services:
  postgresql:
    image: postgres:13.4
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 1024M
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    ports:
      - 127.0.0.1:5432:5432